name: C Unit Tests

permissions:
  contents: read

on:
  push:
    branches:
    - master
  pull_request:
    paths:
    - 'builddefs/**'
    - 'quantum/**'
    - 'platforms/**'
    - 'tmk_core/**'
    - 'tests/**'
    - '*.mk'
    - 'Makefile'
    - '.github/workflows/unit_test.yml'

jobs:
  test:
    runs-on: ubuntu-latest

    container: ghcr.io/qmk/qmk_cli

    steps:
    - name: Disable safe.directory check
      run: git config --global --add safe.directory '*'

    - uses: actions/checkout@v6

    - name: Fetch C test libraries
      run: |
        git clone --depth=1 https://github.com/qmk/googletest lib/googletest
        git clone --depth=1 https://github.com/qmk/printf lib/printf

    - name: Install dependencies
      run: pip3 install -r requirements-dev.txt

    - name: Run C unit tests
      run: make test:all
